coverage:
  status:
    project:
      default:
        # Don't fail PR checks based on coverage (for now)
        informational: true
    patch:
      default:
        # Don't fail PR checks based on patch coverage (for now)
        informational: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "apps/e2e-tests/**"
  - "**/*_test.rs"
  - "**/tests/**"
